### ISSUE TITLE
Add command to apply stash apart from pop

### ISSUE THREAD

**Issue by jmolero** [aacunningham/vim-fuzzy-stash#1]
Thanks for this plugin.

Would it be possible to add a shortcut to apply a stash. Popping a stash is usually more useful but sometimes I miss being able to apply it using this plugin instead of the git command.

**Comment by aacunningham** [comment]
Sorry for the silence, but I've gone ahead and updated the plugin. Just took me a little while to dig back into vimscript. :sweat_smile: 

So the two big changes made are:

1. A new keybinding for `git stash apply`, `ctrl-p`
2. A new configuration option for changing keybindings, `g:fuzzy_stash_actions`

Adding `git stash apply` wasn't terribly hard, but when trying to figure out a good keybinding, I realized that the existing `ctrl-a` would have been better for `apply` and maybe `ctrl-p` should be used for `pop`. This seemed like a bad headache, but I didn't want to change the existing defaults just to make sure I didn't mess with anyone. So, a new configuration variable was added to allow rebinding the actions to different keys.

Pull down the latest from master, take a look at the README, and mess around with it. I did some minimal testing, so everything should be working fine, but feel free to comment on this again if something doesn't quite look right.

Thanks for the suggestion!
